controllers/ProductController.php
<?php

namespace app\controllers;

use yii\web\Controller;
use app\models\Product;
use app\helpers\DateTimeHelper;
use app\helpers\CurrencyHelper;
use yii\data\Sort;
use yii\data\ActiveDataProvider;
use app\models\Company;
use app\models\Category;
use yii\helpers\Url;
use app\models\Rating;
use app\models\User;
use app\models\Subscription;
use app\models\forms\ProductForm;
use Yii;

class ProductController extends Controller
{
				public function beforeAction($action)
				{
								Yii::$app->user->returnUrl = Yii::$app->request->referrer;
								
								return parent::beforeAction($action);
				}
				
				public function actionUpdate($id)
				{
								$product = Product::findOne(['id' => $id]);
								
								if ($product !== null)
								{
												$form = new ProductForm;
												
												if ($form->load(Yii::$app->request->post()) && $form->update($product->id))
												{
																Yii::$app->session->setFlash('success', 'The product was updated succesfully.');
																
		              $product = Product::findOne(['id' => $id]);
												}
												
												return $this->render('update', ['model' => $form, 'product' => $product]);
								}
								
								Yii::$app->session->setFlash('danger', 'This product does not exist.');
								return $this->goBack();
				}
				
    public function actionList($sort = null, $onlyApproved = 1, $search = null)
    {
								$sort = new Sort([
												'attributes' => [
																'name',
																'company.name',
																'category.name',
																'unifiedPrice' => [
																				'asc' => ['priceCacheUSD' => SORT_ASC],
																				'desc' => ['priceCacheUSD' => SORT_DESC],
																				'default' => SORT_ASC,
																],
												],
								]);
								
								$query = Product::find()->joinWith(['company', 'category']);
								$query = $onlyApproved ? $query->where(['product.status' => Product::STATUS_APPROVED]) : $query;
								$query = $search !== null ? $query->where('product.name LIKE :name', [':name' => '%'.$search.'%']) : $query;
								
								$query = $query->orderBy($sort->orders);
								
							 $provider = new ActiveDataProvider([
												'query' => $query,
												'pagination' => [
																'pageSize' => $onlyApproved ? 25 : 10,
												],
												'sort' => $sort,
								]);
								
        return $this->render('//product/list', [
												'sort' => ['attributes' => ['name', 'company.name', 'category.name', 'unifiedPrice']],
												'provider' => $provider,
												'onlyApproved' => $onlyApproved,
												'search' => $search,
								]);
    }
				
				public function actionRate($rating, $product)
				{
								if (!Yii::$app->user->isGuest)
								{
												if (is_numeric($rating))
												{
																$uid = Yii::$app->user->identity->id;

																$p = Product::findOne(['id' => $product]);
																if ($p)
																{
																				$r = Rating::findOne(['userId' => $uid, 'productId' => $product]);
																				if (empty($r))
																				{
																								$r = new Rating;
																				}

																				$r->rating = $rating;
																				$r->userId = $uid;
																				$r->productId = $product;

																				$r->save();
																}
																else
																{
																				Yii::$app->session->setFlash('danger', 'The product does not exist');
																}
												}
												else
												{
																Yii::$app->session->setFlash('danger', 'The rating must be a numeric value');
												}
												
												return $this->redirect(Url::to(['product/list']));
								}
								else
								{
												return $this->redirect(Url::to(['site/signin']));
								}
				}
    
    public function actionCreate()
    {
								Yii::$app->user->returnUrl = Url::to(['product/create']);
								
        if (!Yii::$app->user->isGuest)
								{
												$form = new Product;
												
												if (!empty(Yii::$app->request->post()['Product']))
												{
																$good = 0;
																$total = 0;
																
																$items = Yii::$app->request->post()['Product'];
																
																foreach ($items as $item)
																{
																				if ($item['name'] && $item['url'] && $item['priceElement'])
																				{
																								if (Product::create($item)) { $good++; }
																								$total++;
																				}
																}
																
																if ($good == $total && $total > 0) { Yii::$app->session->setFlash('success', "$good of $total products were added to the database."); }
																if ($good != $total && $good > 0 && $total > 0) { Yii::$app->session->setFlash('warning', "$good of $total products were added to the database."); }
																if ($good == 0 && $total > 0) { Yii::$app->session->setFlash('danger', "$good of $total products were added to the database."); }
																if ($total == 0) { Yii::$app->session->setFlash('warning', "You didn't input any data!"); }
																
												}
												
												$categories = Category::find()->select('name')->all();
												$companies = Company::find()->orderBy('status DESC, name ASC')->all();
												$categoriesArr = [];
												$companiesArr = [];
												
												foreach ($categories as $category)
												{
																$categoriesArr[] = $category->name;
												}
												foreach ($companies as $company)
												{
																$companiesArr[] = $company->status == Company::STATUS_NEW ? $company->name.' (!)' : $company->name;
												}
								
												$categoriesJSON = json_encode($categoriesArr);
												$companiesJSON = json_encode($companiesArr);
												
												return $this->render('create', [
																'model' => $form,
																'categories' => $categoriesJSON,
																'companies' => $companiesJSON,
												]);
								}
								else
								{
												return $this->redirect(Url::to(['site/login']));
								}
    }
				
				public function actionApprove($id)
				{
								if (!Yii::$app->user->isGuest && Yii::$app->user->identity->role == User::ROLE_ADMIN)
								{												
												$product = (new Product)->getById($id);
												if ($product !== null)
												{
																$product->status = Product::STATUS_APPROVED;
																$product->save();
												}
												
												return $this->goBack();
								}
								else
								{
												return $this->redirect(Url::to(['site/login']));
								}
				}
    
    public function actionDelete($id)
    {
        if (!Yii::$app->user->isGuest && Yii::$app->user->identity->role == User::ROLE_ADMIN)
								{												
												$product = (new Product)->getById($id);
												if ($product !== null) 
												{ 
																Subscription::deleteAll(['productId' => $id]);
																$product->delete(); 
												}
												
												return $this->goBack();
								}
								else
								{
												return $this->redirect(Url::to(['site/login']));
								}
    }
				
				public function actionHelp()
				{
								return $this->render('help');
				}
				
				public function actionAjaxConvert($value, $from, $to)
				{
								return Yii::$app->formatter->asCurrency(CurrencyHelper::convert($value, $from, $to), CurrencyHelper::getSymbol($to));
				}
				
				public function actionAjaxPrice($id)
				{
							 $p = Product::findOne(['id' => $id]);
								
								if (is_numeric($p->price) && $p->price != 0)
								{
												return Yii::$app->formatter->asCurrency($p->price, CurrencyHelper::getSymbol($p->priceCurrency));
								}	
								throw new Exception('Price retrieve error');
				}
				
				public function actionAjaxCheckUrl($url)
				{						
								if (filter_var($url, FILTER_VALIDATE_URL))
								{
												stream_context_set_default(['http' => ['method' => 'HEAD']]);
												
												$headers = @get_headers($url);
												
												if($headers)
												{
																return $headers[0];
												}
												return '404';
								}
								
								return 'Not an URL';
				}
}

controllers/UserController.php
<?php

namespace app\controllers;

use Yii;
use yii\web\Controller;
use yii\helpers\Url;
use app\models\Subscription;
use app\models\User;
use app\models\forms\SettingsForm;
use app\models\forms\PasswordChangeForm;
use app\models\Product;

class UserController extends Controller
{
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }
				
				public function actionUpdate()
				{
							 if (!Yii::$app->user->isGuest)
								{
												$model = new SettingsForm;
												$modelPassword = new PasswordChangeForm;
												$user = Yii::$app->user->identity;
												
												if($model->load(Yii::$app->request->post()) && $model->update())
												{
																Yii::$app->session->setFlash('success', 'Your account was succesfully updated.');
												}
												
												if($modelPassword->load(Yii::$app->request->post()) && $modelPassword->updatePassword())
												{
																Yii::$app->session->setFlash('success', 'Your password was sucessfully changed.');
												}
												
												if(!$model->hasErrors())
												{
																$model->username = $user->username;
																$model->email = $user->email;
																$model->currency = $user->currency;
												}
												
												return $this->render('update', ['model' => $model, 'modelPassword' => $modelPassword]);
								}
								else
								{
												return $this->redirect(Url::to(['site/login']));
								}
				}
				
				public function actionAjaxDetails($id)
				{
								$user = User::findOne(['id' => $id]);
								
								$return = new \stdClass;
								
								$return->id = $user->id;
								$return->username = $user->username;
								$return->email = $user->email;
								$return->timeCreated = $user->timeCreated;
								$return->status = $user->statusBadge;
								$return->role = $user->roleBadge;
								$return->currency = $user->currency;
								$return->productsApproved = Yii::$app->db->createCommand('SELECT COUNT(*) FROM product WHERE status = :status AND authorId = :uid', [':status' => Product::STATUS_APPROVED, ':uid' => $user->id])->queryAll()[0]['COUNT(*)'];
								$return->productsUnapproved = Yii::$app->db->createCommand('SELECT COUNT(*) FROM product WHERE status = :status AND authorId = :uid', [':status' => Product::STATUS_NEW, ':uid' => $user->id])->queryAll()[0]['COUNT(*)'];
								
								return json_encode($return);
				}
}

views/admin/consoleLog.php
<?php

$patterns = [
				'#(\[IMPORTANT\].*?)<br/>#i' => '<span class="log-important">$1</span><br/>',
				'#(\[WARNING\].*?)<br/>#i' => '<span class="log-warning">$1</span><br/>',
				'#(\[ERROR\].*?)<br/>#i' => '<span class="log-error">$1</span><br/>',
				'#(\[SUMMARY\].*?)<br/>#i' => '<span class="log-summary">$1</span><br/>',
];

?>

<div id="admin">
				<pre style="font-family: monospace">
								<?php 
								
								$a = str_replace("\n", '<br/>', $log);
								
								foreach($patterns as $pattern => $replace)
								{
												$a = preg_replace($pattern, $replace, $a);
								}
								
								echo $a;
												
								?>
				</pre>
</div>

<style type="text/css">
.log-important
{
				color: #ddaa00;
}
.log-summary
{
				color: #080;
}
.log-warning
{
				color: #FF8A00;
}
.log-error
{
				color: #f00;
}
</style>

views/admin/listProducts.php
<?php

use yii\helpers\Url;
use app\models\Product;
use app\helpers\AlertHelper;
use app\helpers\CurrencyHelper;
use app\models\Subscription;
use yii\grid\GridView;
use yii\data\ActiveDataProvider;

?>

<div id="admin">
				
				<?= AlertHelper::get() ?>
				
				<?php GridView::begin([
								'id' => 'admin-list-products',
								'dataProvider' => new ActiveDataProvider([
												'query' => Product::find(),
												'pagination' => [
																'pageSize' => 50,
												],
								]),
								'columns' => [
												['class' => yii\grid\SerialColumn::className()],
												'name' => [
																'format' => 'raw',
																'label' => 'Name',
															 'value' => function($data)
																{
																				$name = $data->name;
																				
																				if (strlen($name) > 35)
																				{
																								$name = substr($name, 0, 35).'...';
																				}
																				
																				$name = '<span title="'.$data->name.'">'.$name.'<span style="hidden"><span>';
																				
																				return $name;
																},
																'attribute' => 'name',
																'contentOptions' => ['class' => 'nowrap'],
												],
												'status' => [
																'format' => 'raw',
																'label' => 'Status',
																'attribute' => 'status',
																'value' => function($data){
																				return '<span>'.$data->getStatusBadge().'</span>';
																},
																'contentOptions' => ['class' => 'nowrap text-center'],
												],
												'url' => [
																'format' => 'raw',
																'label' => 'Website',
															 'value' => function($data)
																{
																				$url = $data->url;
																				
																				if (strlen($url) > 30)
																				{
																								$url = substr($url, 0, 30).'...';
																				}
																				
																				$url = '<a data-url="'.$data->url.'" href="'.$data->url.'" title="'.$data->url.'">'.$url.'</a> <span class="url-info pull-right"></span>';
																				
																				return $url;
																},
																'attribute' => 'url',
																'contentOptions' => ['class' => 'nowrap url'],
												],
												'priceElement' => [
																'format' => 'raw',
																'label' => 'CSS path',
															 'value' => function($data)
																{
																				$path = $data->priceElement;
																				
																				if (strlen($path) > 30)
																				{
																								$path = '...'.substr($path, strlen($path) - 30);
																				}
																				
																				$path = '<span title="'.$data->priceElement.'">'.$path.'</span>';
																				
																				return $path;
																},
																'contentOptions' => ['class' => 'nowrap'],
												],
												'author' => [
																'attribute' => 'author.username',
																'label' => 'Author',
																'format' => 'raw',
																'value' => function ($data){
																				return isset($data->author) ? '<span data-id="'.$data->author['id'].'">'.$data->author['username'].'</span>' : null;
																},
																'contentOptions' => ['class' => 'user'],
												],
												'timeAdded' => [
																'format' => 'raw',
																'label' => 'Added',
																'value' => function($data){
																				$date = Yii::$app->formatter->asDate($data->timeAdded, 'php:d F Y');
																				$time = Yii::$app->formatter->asTime($data->timeAdded);
																				return '<span class="datetimeToggle" data-shown="date" data-time="'.$time.'" data-date="'.$date.'">'.$date.'</span>';
																},
																'attribute' => 'timeAdded',
																'contentOptions' => ['class' => 'nowrap'],
												],
												'price' => [
																'format' => 'raw',
																'label' => 'Price',
																'value' => function($data){
																				return '<span data-id="'.$data->id.'" class="price"><i class="fa fa-gear fa-spin"></i></span>';
																},
																'contentOptions' => ['class' => 'nowrap'],
												],
												'action' => [
																'format' => 'raw',
																'value' => function($data){
																				$buttons = '';
																				$subscribed = false;
																				
																				if (Subscription::findOne(['productId' => $data->id]) !== null)
																				{
																								$subscribed = true;
																				}																	
																				
																				$buttons .= '<a href="'.Url::to(['product/update', 'id' => $data->id]).'" style="color: #444"><i class="fa fa-pencil fa-fw"></i></a>';
																				$buttons .= ' <a class="remove" onclick="'.($subscribed ? 'return stopLink();' : '').'" href="'.Url::to(['product/delete', 'id' => $data->id]).'" style="color: #944"><i class="fa fa-trash fa-fw"></i></a>';
																				$buttons .= $data->status == Product::STATUS_NEW ? ' <a href="'.Url::to(['product/approve', 'id' => $data->id]).'" style="color: #494"><i class="fa fa-check"></i></a>' : null;
															
																				return $buttons;
																},
																'contentOptions' => ['class' => 'nowrap text-center'],
												],
												'subscription' => [
																'format' => 'raw',
																'value' => function($data){
																				$subscribed = false;
																				
																				if (Subscription::findOne(['productId' => $data->id]) !== null)
																				{
																								$subscribed = true;
																				}
																				
																				return $subscribed ? '<i class="fa fa-envelope" style="color: #444"></i>' : '';
																}
												],
								],
				]); ?>
				
				<?php GridView::end(); ?>
</div>

<script type="text/javascript">
				
function stopLink()
{
				return confirm('Are you sure you want to delete this product? Users are subscribed to it.');
}
				
$(document).ready(function(){
				$('#admin-list-products table tbody tr td.user').click(function(){
								var uid = $(this).find('span').data('id');
								console.log(uid);
								if (uid !== undefined)
								{
												$('.sidebar-container .user-info .header .working').show();
												
												$.ajax({
																url: '<?= Url::to(['user/ajax-details']) ?>?id='+uid,
																method: 'get'
												}).done(function(data){
																var user = JSON.parse(data);

																$('.sidebar-container .user-info .header .working').hide();
																
																$('.sidebar-container .user-info .content').html(
																				'<table>'
																								+'<tr><td class="b">Id</td><td>' + user.id + '</td></tr>'
																								+'<tr><td class="b">Username</td><td>' + user.username + '</td></tr>'
																								+'<tr><td class="b">Email</td><td>' + user.email + '</td></tr>'
																								+'<tr><td class="b">Created</td><td>' + user.timeCreated + '</td></tr>'
																								+'<tr><td class="b">Status</td><td>' + user.status + '</td></tr>'
																								+'<tr><td class="b">Role</td><td>' + user.role + '</td></tr>'
																								+'<tr><td class="b">Products added</td><td><span class="b" style="color: #080">' + user.productsApproved + '</span>' + (user.productsUnapproved !== undefined ? (' | <span class="b" style="color: #b80">' + user.productsUnapproved + '</span>') : '') + '</td></tr>'
																				+'</table>'
																);
												});			
								}
								else
								{
												$('.sidebar-container .user-info .content').html('<i>No user selected</i>');
												$('.sidebar-container .user-info .header .working').hide();
								}
				});
				
				$('#admin-list-products table tbody tr').each(function(){
								var id = $(this).find('span.price').data('id');
								
								$.ajax({
												url: '<?= Url::to(['product/ajax-price']) ?>?id='+id,
											 method: 'get',
								}).done(function(data){
												update(id, data, 'price');
								}).fail(function(){
												update(id, false, 'price');
								});
				});
			
				$('#admin-list-products table tbody tr td.url').click(function(){				
				
								var id = $(this).parent('tr').find('span.price').data('id');
								var urlToCheck = $(this).find('a').data('url');
								
								$(this).find('.url-info').html('<i class="fa fa-gear fa-spin"></i>');
								
								$.ajax({
												url: '<?= Url::to(['product/ajax-check-url']) ?>?url='+urlToCheck,
											 method: 'get',
								}).done(function(data){
												update(id, data, 'url');
								});
				});
				
				$('.datetimeToggle').parent('td').click(function(){toggle($(this).find('.datetimeToggle'))});
				$('.datetimeToggle').parent('td').hover(function(){toggle($(this).find('.datetimeToggle'));}, function(){toggle($(this).find('.datetimeToggle'));});
});		

function toggle(obj, hard)
{
				if (obj.data('shown') === 'date')
				{
								obj.data('shown', 'time');
								obj.text(obj.data('time'));
				}
				else
				{
								obj.data('shown', 'date');
								obj.text(obj.data('date'));
				}
}

function update(id, data, type)
{
				if (type === 'price')
				{
								if (data !== false)
								{
												$('#admin-list-products table tbody tr[data-key='+id+'] .price').text(data);
								}
								else
								{
												$('#admin-list-products table tbody tr[data-key='+id+'] .price').html('<span class="label label-danger">Error</span>');
								}
				}
				if (type === 'url')
				{
								var obj = $('#admin-list-products table tbody tr[data-key='+id+'] .url .url-info');
								if (data.indexOf('200') > -1)
								{
												obj.html('<i class="fa fa-check" style="color: #080;"></i>');
								}
								else
								{
												obj.html('<span class="label label-danger">'+data+'</span>');
								}
				}
}
</script>

views/admin/listUsers.php
<?php

use yii\helpers\Url;
use app\models\User;
use app\helpers\AlertHelper;
use app\helpers\CurrencyHelper;
use app\models\Subscription;
use yii\grid\GridView;
use yii\data\ActiveDataProvider;

?>

<div id="admin">
				
				<?= AlertHelper::get() ?>
				
				<?php GridView::begin([
								'id' => 'admin-list-users',
								'dataProvider' => new ActiveDataProvider([
												'query' => User::find(),
												'pagination' => [
																'pageSize' => 50,
												],
								]),
								'columns' => [
												['class' => yii\grid\SerialColumn::className()],
												'username:text:Username',
												'email:text:Email',
												'timeCreated:datetime:Created',
												'status' => [
																'format' => 'html',
																'value' => function($data){
																				return $data->statusBadge;
																},
																'label' => 'Status',
												],
												'role' => [
																'format' => 'html',
																'value' => function($data){
																				return $data->roleBadge;
																},
																'label' => 'Role',
												],
												'action' => [
																'format' => 'raw',
																'value' => function($data){
																				$buttons = '';
																				$subscribed = false;
																				
																				if (Subscription::findOne(['productId' => $data->id]) !== null)
																				{
																								$subscribed = true;
																				}																	
																				
																				return $data->status != User::STATUS_SUSPENDED 
																								?	'<a href="'.Url::to(['user/ban', 'id' => $data->id]).'"><i class="fa fa-ban text-danger"></i></a>' 
																								:	'<a href="'.Url::to(['user/unban', 'id' => $data->id]).'"><i class="fa fa-ban text-info"></i></a>';
																},
																'contentOptions' => ['class' => 'nowrap text-center'],
												],
								],
				]); ?>
				
				<?php GridView::end(); ?>
</div>