models/Subscription.php
<?php

namespace app\models;

use yii\db\ActiveRecord;
use Yii;
use app\helpers\DateTimeHelper;

class Subscription extends ActiveRecord
{
				const ITEMS_PER_PAGE = 20;
				
				public static function tableName()	
				{
							 return 'subscription';
				}
				
				public static function getByUser($userId, $page = 1)
				{
								$offset = ($page - 1) * self::ITEMS_PER_PAGE;
								
								return self::find()->joinWith('product')->offset($offset)->limit(self::ITEMS_PER_PAGE)->where(['userId' => $userId])->all();
				}
				
				public function getProduct()
				{
								return $this->hasOne(Product::className(), ['id' => 'productId']);
				}
				
				/**
				 * 
				 * @param Product/integer $product - Product object or product id
				 * @param boolean $logFlashes - Determines whether to set flashes.
				 * @return integer/boolean true or false whether the update was succesful. Will also return false if object with the same user and product id already exists.
				 */
				public static function create($product, $logFlashes = true)
				{
								$user = Yii::$app->user->identity;

								$_product = ($product instanceof Product) ? $product : Product::findOne(['id' => $product, 'status' => Product::STATUS_APPROVED]);
												
								$subscription = Subscription::findOne(['productId' => $_product->id, 'userId' => $user->id]);

								if ($subscription === null)
								{
												$subscription = new Subscription;

												$subscription->userId = $user->id;
												$subscription->productId = $_product->id;
												$subscription->timeAdded = DateTimeHelper::now();

												if ($subscription->save())
												{
																if ($logFlashes) { Yii::$app->session->setFlash('success', "Your subscription for product $_product->name has been succesfully registered."); }
																return true;
												}
												else
												{
																if ($logFlashes) { Yii::$app->session->setFlash('danger', "There was an error while processing your request. Please try again in a few minutes. If the problem persists, please contact us."); }
																return false;
												}
								}
								else
								{
												if ($logFlashes) { Yii::$app->session->setFlash('danger', "You have already subscribed to this product."); }
												return false;
								}
				}
}

controllers/SubscriptionController.php
<?php

namespace app\controllers;

use Yii;
use yii\web\Controller;
use app\models\Subscription;
use app\models\Product;
use yii\helpers\Url;
use app\models\Company;

class SubscriptionController extends Controller
{
				public function beforeAction($action)	
				{
								Yii::$app->user->returnUrl = Yii::$app->request->referrer;
								
								return parent::beforeAction($action);
				}
				
				public function actionAdd($product)
				{
								if (!Yii::$app->user->isGuest)
								{
												Subscription::create($product);
												
												$this->goBack();
								}
								else
								{
												return $this->redirect(Url::to(['site/login']));
								}
				}
				
				public function actionAddByCompany($company)
				{
								if (!Yii::$app->user->isGuest)
								{
												$products = Product::findAll(['companyId' => $company, 'status' => Product::STATUS_APPROVED]);
												$user = Yii::$app->user->identity;

												$success = 0;
												$total = 0;

												foreach ($products as $product)
												{
																$total++;
																$success += Subscription::create($product, false) ? 1 : 0;
												}

												if ($success > 0 && $total > 0) { Yii::$app->session->setFlash('success', "$success out of $total products were added to your subscription list."); }
												else if ($success == 0 && $total > 0) { Yii::$app->session->setFlash('warning', "$success out of $total products were added to your subscription list. Probably you already subscribed to them."); }
												else if (total == 0) { Yii::$app->session->setFlash('danger', "This company has no products."); }

												$this->goBack();
								}
								else
								{
												return $this->redirect(Url::to(['site/login']));
								}
				}
				
				public function actionRemove($product)
				{
								if (!Yii::$app->user->isGuest)
								{
												$user = Yii::$app->user->identity;
												
												$subscription = Subscription::findOne(['productId' => $product, 'userId' => Yii::$app->user->identity->id]);
												$product = Product::findOne(['id' => $product]);
												
												if ($subscription === null)
												{
																Yii::$app->session->setFlash('warning', "You haven't subscribed to that product.");
												}
												else
												{
																if ($subscription->delete() !== false)
																{
																				Yii::$app->session->setFlash('success', "Your subscription for product $product->name was succesfully removed.");
																}
																else
																{
																				Yii::$app->session->setFlash('danger', "There was an error while processing your request. Please try again in a few minutes. If the problem persists, please contact us.");
																}
												}
												
												$this->goBack();
								}
								else
								{
												return $this->redirect(Url::to(['site/login']));
								}
				}
				
				public function actionList($page = 1)
				{
								if (!Yii::$app->user->isGuest)
								{
												$user = Yii::$app->user->identity;
												
												$pages = ceil(Yii::$app->db->createCommand('SELECT COUNT(*) FROM subscription WHERE userId = '.$user->id)->queryAll()[0]['COUNT(*)'] / Subscription::ITEMS_PER_PAGE);
								
											 $model = Subscription::getByUser(Yii::$app->user->identity->id, $page);
												
												if ($page > $pages) { $page = $pages; }
												
												if (empty($model))
												{
																Yii::$app->session->setFlash('info', 'You have no subscriptions yet.');
												}
												
												$companies = Company::find()->orderBy('name')->all();
												
												return $this->render('list', ['subscriptions' => $model, 'companies' => $companies, 'pages' => $pages, 'page' => $page]);
								}
								else
								{
												return $this->redirect(Url::to(['site/login']));
								}
				}
}

views/subscription/list.php
<?php

use app\helpers\AlertHelper;
use yii\helpers\Url;
use yii\helpers\Html;
use app\helpers\PaginationHelper;
use yii\grid\GridView;
use yii\data\ActiveDataProvider;
use app\models\Subscription;


echo AlertHelper::get();

echo GridView::widget([
				'id' => 'list-subscriptions',
				'summary' => '',
				'dataProvider' => new ActiveDataProvider([
								'query' => Subscription::find()->where(['userId' => Yii::$app->user->identity->id]),
								'pagination' => [
												'pageSize' => 50,
								],
				]),
				'columns' => [
								'name' => [
												'label' => 'Name',
												'format' => 'html',
												'value' => function($data){
																return Html::a($data->product['name'], $data->product['url']);
												}
								],
								'timeAdded:datetime:Added',
								'remove' => [
												'label' => 'Remove',
												'format' => 'raw',
											 'value' => function($data){
																return '<a href="'.Url::to(['subscription/remove', 'product' => $data->product['id']]).'"><i class="glyphicon glyphicon-remove"></i></a>';
												},
												'contentOptions' => ['class' => 'text-right remove'],
								]
				]
]); ?>

<div class="subscription-add bg-info alert col-md-5">
				<div>
								<p>To subscribe to all products from a producer, select the company below and press <b>Add all.</b></p>
				</div>
				<form method="get" action="<?= Url::to(['subscription/add-by-company']) ?>">
				<div class="form">
								<div class="col-xs-10">
								<select class="form-control" name="company">
												<?php foreach ($companies as $company): ?>
																<option value="<?= $company->id ?>"><?= $company->name ?></option>
												<?php endforeach; ?>
								</select>
								</div>
								<div class="col-xs-2">
												<input type="submit" value="Add all" class="btn btn-danger btn-md" />
								</div>
				</div>
				</form>
</div>