controllers/AdminController.php
<?php

namespace app\controllers;

use yii\web\Controller;
use app\models\User;
use yii\helpers\Url;
use app\models\Product;
use app\models\Company;
use Yii;

class AdminController extends Controller
{
				public function beforeAction($action)
				{
								if (!Yii::$app->user->isGuest && Yii::$app->user->identity->role == User::ROLE_ADMIN)
								{
												return parent::beforeAction($action);
								}
								
								return $this->redirect(Url::to(['site/login']));
				}
				
				public function actionListUsers()
				{
								$users = User::find()->all();
								
								return $this->render('listUsers', ['users' => $users]);
				}
				
				public function actionListProducts()
				{
								$products = Product::find()->all();
								
								return $this->render('listProducts', ['products' => $products]);
				}
				
				public function actionDeleteUser($id)
				{
								$user = User::findOne(['id' => $id]);
								
								return $this->redirect(Url::to(['admin/list-users']));
				}
				
				public function actionListCompanies()
				{
								$companies = Company::find()->all();
								
								return $this->render('listCompanies', ['companies' => $companies]);
				}
				
				public function actionConsoleLog()
				{
								$log = file_get_contents(Url::to('@runtime/logs/console.log'));
								
								return $this->render('consoleLog', ['log' => $log]);
				}
}

controllers/SubscriptionController.php
<?php

namespace app\controllers;

use Yii;
use yii\web\Controller;
use app\models\Subscription;
use app\models\Product;
use yii\helpers\Url;
use app\models\Company;

class SubscriptionController extends Controller
{
				public function beforeAction($action)	
				{
								Yii::$app->user->returnUrl = Yii::$app->request->referrer;
								
								return parent::beforeAction($action);
				}
				
				public function actionAdd($product)
				{
								if (!Yii::$app->user->isGuest)
								{
												Subscription::create($product);
												
												$this->goBack();
								}
								else
								{
												return $this->redirect(Url::to(['site/login']));
								}
				}
				
				public function actionAddByCompany($company)
				{
								if (!Yii::$app->user->isGuest)
								{
												$products = Product::findAll(['companyId' => $company, 'status' => Product::STATUS_APPROVED]);
												$user = Yii::$app->user->identity;

												$success = 0;
												$total = 0;

												foreach ($products as $product)
												{
																$total++;
																$success += Subscription::create($product, false) ? 1 : 0;
												}

												if ($success > 0 && $total > 0) { Yii::$app->session->setFlash('success', "$success out of $total products were added to your subscription list."); }
												else if ($success == 0 && $total > 0) { Yii::$app->session->setFlash('warning', "$success out of $total products were added to your subscription list. Probably you already subscribed to them."); }
												else if (total == 0) { Yii::$app->session->setFlash('danger', "This company has no products."); }

												$this->goBack();
								}
								else
								{
												return $this->redirect(Url::to(['site/login']));
								}
				}
				
				public function actionRemove($product)
				{
								if (!Yii::$app->user->isGuest)
								{
												$user = Yii::$app->user->identity;
												
												$subscription = Subscription::findOne(['productId' => $product, 'userId' => Yii::$app->user->identity->id]);
												$product = Product::findOne(['id' => $product]);
												
												if ($subscription === null)
												{
																Yii::$app->session->setFlash('warning', "You haven't subscribed to that product.");
												}
												else
												{
																if ($subscription->delete() !== false)
																{
																				Yii::$app->session->setFlash('success', "Your subscription for product $product->name was succesfully removed.");
																}
																else
																{
																				Yii::$app->session->setFlash('danger', "There was an error while processing your request. Please try again in a few minutes. If the problem persists, please contact us.");
																}
												}
												
												$this->goBack();
								}
								else
								{
												return $this->redirect(Url::to(['site/login']));
								}
				}
				
				public function actionList($page = 1)
				{
								if (!Yii::$app->user->isGuest)
								{
												$user = Yii::$app->user->identity;
												
												$pages = ceil(Yii::$app->db->createCommand('SELECT COUNT(*) FROM subscription WHERE userId = '.$user->id)->queryAll()[0]['COUNT(*)'] / Subscription::ITEMS_PER_PAGE);
								
											 $model = Subscription::getByUser(Yii::$app->user->identity->id, $page);
												
												if ($page > $pages) { $page = $pages; }
												
												if (empty($model))
												{
																Yii::$app->session->setFlash('info', 'You have no subscriptions yet.');
												}
												
												$companies = Company::find()->orderBy('name')->all();
												
												return $this->render('list', ['subscriptions' => $model, 'companies' => $companies, 'pages' => $pages, 'page' => $page]);
								}
								else
								{
												return $this->redirect(Url::to(['site/login']));
								}
				}
}

controllers/UserController.php
<?php

namespace app\controllers;

use Yii;
use yii\web\Controller;
use yii\helpers\Url;
use app\models\Subscription;
use app\models\User;
use app\models\forms\SettingsForm;
use app\models\forms\PasswordChangeForm;
use app\models\Product;

class UserController extends Controller
{
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }
				
				public function actionUpdate()
				{
							 if (!Yii::$app->user->isGuest)
								{
												$model = new SettingsForm;
												$modelPassword = new PasswordChangeForm;
												$user = Yii::$app->user->identity;
												
												if($model->load(Yii::$app->request->post()) && $model->update())
												{
																Yii::$app->session->setFlash('success', 'Your account was succesfully updated.');
												}
												
												if($modelPassword->load(Yii::$app->request->post()) && $modelPassword->updatePassword())
												{
																Yii::$app->session->setFlash('success', 'Your password was sucessfully changed.');
												}
												
												if(!$model->hasErrors())
												{
																$model->username = $user->username;
																$model->email = $user->email;
																$model->currency = $user->currency;
												}
												
												return $this->render('update', ['model' => $model, 'modelPassword' => $modelPassword]);
								}
								else
								{
												return $this->redirect(Url::to(['site/login']));
								}
				}
				
				public function actionAjaxDetails($id)
				{
								$user = User::findOne(['id' => $id]);
								
								$return = new \stdClass;
								
								$return->id = $user->id;
								$return->username = $user->username;
								$return->email = $user->email;
								$return->timeCreated = $user->timeCreated;
								$return->status = $user->statusBadge;
								$return->role = $user->roleBadge;
								$return->currency = $user->currency;
								$return->productsApproved = Yii::$app->db->createCommand('SELECT COUNT(*) FROM product WHERE status = :status AND authorId = :uid', [':status' => Product::STATUS_APPROVED, ':uid' => $user->id])->queryAll()[0]['COUNT(*)'];
								$return->productsUnapproved = Yii::$app->db->createCommand('SELECT COUNT(*) FROM product WHERE status = :status AND authorId = :uid', [':status' => Product::STATUS_NEW, ':uid' => $user->id])->queryAll()[0]['COUNT(*)'];
								
								return json_encode($return);
				}
}

views/layouts/main.php
<?php
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;
use yii\helpers\Url;
use app\models\User;

/* @var $this \yii\web\View */
/* @var $content string */

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
				<link rel="icon" type="ico" href="<?= Url::to('@web/favicon.ico') ?>" />
    <title><?= Html::encode($this->title) ?></title>
				<script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
				<link rel="stylesheet" href="http://css-spinners.com/css/spinner/three-quarters.css" type="text/css">
				<link href="<?= Url::to('@web/css/font.css') ?>" rel="stylesheet" />
				<script type="text/javascript" src="<?= Url::to('@web/js/rate.js')?>"></script>
				<script type="text/javascript" src="<?= Url::to('@web/js/widths.js')?>"></script>
				<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
				<link rel="stylesheet" type="text/css" href="<?= Url::to('@web/css/bootstrap.css') ?>">
				<link rel="stylesheet" type="text/css" href="<?= Url::to('@web/css/font-awesome.css') ?>">
				<script type="text/javascript">
				/* To initialize BS3 tooltips set this below */
				$(function () { 
								$("[data-toggle='tooltip']").tooltip(); 
				});;
				/* To initialize BS3 popovers set this below */
				$(function () { 
								$("[data-toggle='popover']").popover(); 
				});
				$(function () {
								$(".dropdown-toggle").dropdown();
				})
				</script>
    <?php $this->head() ?>
			 
</head>
<body>

<?php $this->beginBody() ?>
    <div class="wrap <?= '_'.Yii::$app->controller->id ?> <?= '_'.Yii::$app->controller->action->id ?>">
        <?php
            NavBar::begin([
                'brandLabel' => 'Unisoned',//Html::img(Url::to('@web/img/unisoned_b_1.png'), ['height' => 70]),
                'brandUrl' => Yii::$app->homeUrl,
                'options' => [
                    'class' => 'navbar-fixed-top',
                ],
            ]);
            echo Nav::widget([
                'options' => ['class' => 'navbar-nav navbar-right'],
																'encodeLabels' => false,
                'items' => [
                    ['label' => '<i class="fa fa-home fa-fw"></i> Home' , 'url' => ['/site/index']],
																				['label' => 'Product list', 'url' => ['/product/list']],
                    ['label' => 'About', 'url' => ['/site/about']],
                    ['label' => 'Contact', 'url' => ['/site/contact']],
                    Yii::$app->user->isGuest ?
                        ['label' => '<i class="fa fa-sign-in fa-fw"></i> Login', 'url' => ['/site/login']] :
                        [
																												'label' => '<i class="fa fa-user"></i> '.Yii::$app->user->identity->username,
																												'items' => [
																																['label' => '<i class="fa fa-envelope fa-fw"></i> Email subscriptions <span class="badge">'.Yii::$app->db->createCommand('SELECT COUNT(*) FROM subscription WHERE userId = '.Yii::$app->user->identity->id)->queryAll()[0]['COUNT(*)'].'</span>', 'url' => ['/subscription/list']],
																																['label' => '<i class="fa fa-plus-circle fa-fw"></i> Add product', 'url' => ['/product/create']],
																																'<li class="divider"></li>',
																																['label' => '<i class="fa fa-gear fa-fw"></i> Settings', 'url' => ['/user/update']],
																																['label' => '<i class="fa fa-gears fa-fw"></i> Admin panel', 'url' => ['/admin/list-products', 'p' => 0], 'visible' => !Yii::$app->user->isGuest && Yii::$app->user->identity->role == User::ROLE_ADMIN],
																																'<li class="divider"></li>',
																																['label' => '<i class="fa fa-sign-out fa-fw"></i> Logout', 'url' => ['/user/logout']],
																												],
																								],
                ],
            ]);
            NavBar::end();
        ?>
								
        <div class="container">
												<?php if  (Yii::$app->controller->id == 'admin'): ?>
												<div class="sidebar-container col-lg-3 col-sm-5">
																<div class="sidebar">
																				<div class="header">
																								Admin panel
																				</div>
																				<?php echo Nav::widget([
																								'options' => ['class' => 'nav nav-sidebar'],
																								'encodeLabels' => false,
																								'items' => [
																												['label' => 'Product list' , 'url' => ['/admin/list-products']],
																												['label' => 'User list', 'url' => ['/admin/list-users']],
																												['label' => 'Company list', 'url' => ['/admin/list-companies']],
																												['label' => 'Category list', 'url' => ['/admin/list-categories']],
																												['label' => 'Server log', 'url' => ['/admin/console-log']],
																								],
																				]); ?>
																</div>
																<?php if (Yii::$app->controller->action->id == 'list-products'): ?>
																<div class="user-info">
																				<div class="header">
																								User info
																								<i class="working pull-right fa fa-gear fa-spin fa-2x" style="display: none; position: relative; bottom: 4px;"></i>
																				</div>
																				<div class="content">
																								<i>No user selected</i>
																				</div>
																</div>
																<?php endif; ?>
												</div>
												<?php endif; ?>
												
												<div class="content-wrapper <?= Yii::$app->controller->id == 'admin' ? 'col-lg-9 col-sm-7' : '' ?>">
															 <?= siteHeader(); ?>
																<div class="content"><?= $content ?></div>
												</div>
												<!-- <div class="ads-bottom row">
																<div class="col-xs-4"><img src="<?= Url::to('@web/img/ad_empty.png')?>"/></div>
																<div class="col-xs-4"><img src="<?= Url::to('@web/img/ad_empty.png')?>"/></div>
																<div class="col-xs-4"><img src="<?= Url::to('@web/img/ad_empty.png')?>"/></div>
												</div> -->
        </div>
    </div>
				
    <footer class="footer">
        <div class="container">
            <p class="pull-left">&copy; Radosław Stępiński <?= date('Y') ?></p>
        </div>
    </footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

<?php 
function siteHeader()
{
				$route = Yii::$app->controller->id.'/'.Yii::$app->controller->action->id;
				
				$headers = [
								'site/about' => 'About',
								'site/help' => 'Supported currencies',
								'site/login' => 'Login',
								'site/contact' => 'Contact',
								'site/error' => 'Error',
								'site/resendEmail' => 'Resend activation email',
								'site/signup' => 'Sign up',
								
								'product/list' => 'Product list',
								'product/create' => 'Add products',
								'product/help' => 'Help',
								'product/update' => 'Update product',
								
								'admin/list-products' => 'Product list',
								'admin/console-log' => 'Console log',
								
								'subscription/list' => 'Your subscriptions',
								
								'user/update' => 'Account',
				];
				
				return isset($headers[$route]) ? '<div class="header"><h1 class="no-margin">'.$headers[$route].'</h1></div>' : null;
}
?>