models/Product.php
<?php

namespace app\models;

use yii\db\ActiveRecord;
use app\helpers\UrlFileReadHelper;
use app\helpers\DateTimeHelper;
use yii\data\ActiveDataProvider;
use app\helpers\CurrencyHelper;
use yii\helpers\ArrayHelper;
use Yii;

class Product extends ActiveRecord
{    
				const 
								STATUS_NEW = 0,
								STATUS_APPROVED = 1,
				
								ITEMS_PER_PAGE = 50;
				
				
    public static function tableName() 
    {
        return 'product';
    }
    
    public function fields() 
    {
        $fields = parent::fields();
        
        $fields[] = 'company';
        $fields[] = 'category';
        
        return $fields;
    }
				
				public function attributeLabels()	
				{
							 return [
												'name' => 'Name',
												'url' => 'Website',
												'price' => 'Price',
											 'priceElement' => 'Price CSS path',
												'priceCurrency' => 'Price currency',
								];
				}
    
    public function getCompany()
    {
        return $this->hasOne(Company::className(), ['id' => 'companyId']);
    }
    
    public function getCategory()
    {
        return $this->hasOne(Category::className(), ['id' => 'categoryId']);
    }
				
				public function getAuthor()
				{
								return $this->hasOne(User::className(), ['id' => 'authorId']);
				}
				
				/**
				 * 
				 * @param array $item new product properties
				 */
				
				public static function create($item)
				{	
								$product = Product::findOne(['name' => $item['name'], 'status' => Product::STATUS_APPROVED]);
								
								if ($product === null)
								{
												$product = new Product;

												$product->name = $item['name'];
												$product->url = $item['url'];
												$product->priceElement = $item['priceElement'];

												$product->companyId = Company::findOne(['name' => $item['company']])->id;
												$product->categoryId = Category::findOne(['name' => $item['category']])->id;

												$product->authorId = Yii::$app->user->identity->id;
												$product->timeAdded = DateTimeHelper::now();
												$product->status = Product::STATUS_NEW;

												if ($product->save())
												{
																return true;
												}
								}
								else
								{
												Yii::$app->session->addFlash('danger', "Product $product->name already exists.");
								}
								return false;
				}
				
    public function getById($id)
    {
        return self::findOne(['id' => $id]);
    }
    
    public function getByCategory($category)
    {
        return self::find()
                ->joinWith(['company', 'category'])
                ->where(['categoryId' => $category])
                ->orderBy('company.name ASC, name ASC')
                ->all();
    }
    
    public function getByAuthor($author)
    {
        return self::find()->where(['authorId' => $author])->all();
    }
    
    public function getAll($page, $sort, $onlyApproved)
    {
								$offset = ($page - 1) * self::ITEMS_PER_PAGE;
								
								$condition = $onlyApproved ? ['status' => self::STATUS_APPROVED] : [];
								
								switch($sort)
								{
												case 'price':
																return self::find()->where($condition)->orderBy('priceCacheUSD')->limit(self::ITEMS_PER_PAGE)->offset($offset)->all();
												
												case 'producer':
																return self::find()->where($condition)->joinWith(['company'])->orderBy('company.name, name')->limit(self::ITEMS_PER_PAGE)->offset($offset)->all();
																
												case 'category':
																return self::find()->where($condition)->joinWith(['category'])->orderBy('category.name, name')->limit(self::ITEMS_PER_PAGE)->offset($offset)->all();
																
												default:
																return self::find()->where($condition)->orderBy('name')->limit(self::ITEMS_PER_PAGE)->offset($offset)->all();
								}
    }
    
    public function getPrice()
    {
								if ($this->priceNeedsRefresh)
								{
												return $this->updatePrice();
								}
								else
								{
										  return $this->priceCache;
								}
    }
				
				public function getPriceNeedsRefresh()
				{
								if (DateTimeHelper::compare(DateTimeHelper::add(1, 'days', $this->priceCacheTime), DateTimeHelper::now()) === 1)
								{
												return true;
								}
								if ($this->priceCache == 0)
								{
												return true;
								}
								return false;
				}
				
				public function getStarRating()
				{
								return round($this->getRating());
				}
				
				public function getRating()
				{
								$ratings = Rating::findAll(['productId' => $this->id]);
								
								if (!empty($ratings))
								{
												$count = 0;
												$ratingSum = 0;
												
												foreach ($ratings as $rating)
												{
																$count++;
																$ratingSum += $rating->rating;
												}
												
												return round($ratingSum / $count, 2);
								}
								else
								{
												return false;
								}
				}
				
				public function updatePrice()
				{
        $url = $this->url;
        $element = $this->priceElement;
								
								$doc = \PhpQuery::newDocumentHTML(UrlFileReadHelper::readFile($url));
								
								if ($doc == 'ERR_404') { return 'E_404'; }
								
								\PhpQuery::selectDocument($doc);

								$html = pq($element)->html();
								$matches = [];
								$price = 0;
								
								preg_match_all('#([\$£€ ])+([0-9,\.]+)#', $html, $matches);
								
								if (!isset($matches[0][0]))
								{
												$price = 'Error';
								}
								else
								{
												$price = ((count($matches[2]) > 1) ? $matches[2][1] : $matches[2][0]);
												$price = str_replace(',', '', $price);

												$curr = $matches[0][0];

												if (strpos($curr, '$') !== false) { $this->priceCurrency = 'USD'; }
												if (strpos($curr, '€') !== false) { $this->priceCurrency = 'EUR'; }
												if (strpos($curr, '£') !== false) { $this->priceCurrency = 'GBP'; }
								}
								
								$converter = new CurrencyHelper;
								
								$this->priceCache = $price;
								$this->priceCacheTime = DateTimeHelper::now();
								$this->priceCacheUSD = is_numeric($price) ? $this->priceCurrency == 'USD' ? $price : $converter->convert($price,	$this->priceCurrency,	'USD') : null;
								$this->save();

								return $price;
				}
				
				public function getStatusLabel()
				{
								if (isset(self::enumStatusLabels()[$this->status]))
								{
												return self::enumStatusLabels()[$this->status];
								}
								
								return null;
				}
				
				public function getStatusStyle()
				{
								if (isset(self::enumStatusStyles()[$this->status]))
								{
												return self::enumStatusStyles()[$this->status];
								}
								
								return null;
				}
				
				public function getStatusBadge()
				{
								return '<span class="label label-'.$this->getStatusStyle().'">'.$this->getStatusLabel().'</span>';
				}
				
				public static function enumStatusLabels()
				{
								return [
												self::STATUS_APPROVED => 'Approved',
												self::STATUS_NEW => 'New',
								];
				}
				
				public static function enumStatusStyles()
				{
								return [
												self::STATUS_APPROVED => 'success',
												self::STATUS_NEW => 'warning',
								];
				}
}


controllers/CompanyController.php
<?php

namespace app\controllers;

use yii\web\Controller;
use app\models\Company;
use Yii;

class CompanyController extends Controller
{
				public function beforeAction($action)
				{
								if (!Yii::$app->user->isGuest)
								{
												return parent::beforeAction($action);
								}
								return false;
				}
				
				public function actionCreate($name)
				{
								$company = Company::findOne(['name' => $name]);
								
								if ($company === null)
								{
												$company = new Company;
												$company->name = $name;
												$company->status = Company::STATUS_NEW;
												
												if ($company->save())
												{
																Yii::$app->session->setFlash('success', 'The company was succesfully added. It now has to be approved by the admin.');
												}
												else
												{
																Yii::$app->session->setFlash('danger', 'There was an error while adding the company.');
												}
								}
								else
								{
												Yii::$app->session->setFlash('danger', 'This company already exists.');
								}
								
								return $this->goBack();
				}
}

controllers/ProductController.php
<?php

namespace app\controllers;

use yii\web\Controller;
use app\models\Product;
use app\helpers\DateTimeHelper;
use app\helpers\CurrencyHelper;
use yii\data\Sort;
use yii\data\ActiveDataProvider;
use app\models\Company;
use app\models\Category;
use yii\helpers\Url;
use app\models\Rating;
use app\models\User;
use app\models\Subscription;
use app\models\forms\ProductForm;
use Yii;

class ProductController extends Controller
{
				public function beforeAction($action)
				{
								Yii::$app->user->returnUrl = Yii::$app->request->referrer;
								
								return parent::beforeAction($action);
				}
				
				public function actionUpdate($id)
				{
								$product = Product::findOne(['id' => $id]);
								
								if ($product !== null)
								{
												$form = new ProductForm;
												
												if ($form->load(Yii::$app->request->post()) && $form->update($product->id))
												{
																Yii::$app->session->setFlash('success', 'The product was updated succesfully.');
																
		              $product = Product::findOne(['id' => $id]);
												}
												
												return $this->render('update', ['model' => $form, 'product' => $product]);
								}
								
								Yii::$app->session->setFlash('danger', 'This product does not exist.');
								return $this->goBack();
				}
				
    public function actionList($sort = null, $onlyApproved = 1, $search = null)
    {
								$sort = new Sort([
												'attributes' => [
																'name',
																'company.name',
																'category.name',
																'unifiedPrice' => [
																				'asc' => ['priceCacheUSD' => SORT_ASC],
																				'desc' => ['priceCacheUSD' => SORT_DESC],
																				'default' => SORT_ASC,
																],
												],
								]);
								
								$query = Product::find()->joinWith(['company', 'category']);
								$query = $onlyApproved ? $query->where(['product.status' => Product::STATUS_APPROVED]) : $query;
								$query = $search !== null ? $query->where('product.name LIKE :name', [':name' => '%'.$search.'%']) : $query;
								
								$query = $query->orderBy($sort->orders);
								
							 $provider = new ActiveDataProvider([
												'query' => $query,
												'pagination' => [
																'pageSize' => $onlyApproved ? 25 : 10,
												],
												'sort' => $sort,
								]);
								
        return $this->render('//product/list', [
												'sort' => ['attributes' => ['name', 'company.name', 'category.name', 'unifiedPrice']],
												'provider' => $provider,
												'onlyApproved' => $onlyApproved,
												'search' => $search,
								]);
    }
				
				public function actionRate($rating, $product)
				{
								if (!Yii::$app->user->isGuest)
								{
												if (is_numeric($rating))
												{
																$uid = Yii::$app->user->identity->id;

																$p = Product::findOne(['id' => $product]);
																if ($p)
																{
																				$r = Rating::findOne(['userId' => $uid, 'productId' => $product]);
																				if (empty($r))
																				{
																								$r = new Rating;
																				}

																				$r->rating = $rating;
																				$r->userId = $uid;
																				$r->productId = $product;

																				$r->save();
																}
																else
																{
																				Yii::$app->session->setFlash('danger', 'The product does not exist');
																}
												}
												else
												{
																Yii::$app->session->setFlash('danger', 'The rating must be a numeric value');
												}
												
												return $this->redirect(Url::to(['product/list']));
								}
								else
								{
												return $this->redirect(Url::to(['site/signin']));
								}
				}
    
    public function actionCreate()
    {
								Yii::$app->user->returnUrl = Url::to(['product/create']);
								
        if (!Yii::$app->user->isGuest)
								{
												$form = new Product;
												
												if (!empty(Yii::$app->request->post()['Product']))
												{
																$good = 0;
																$total = 0;
																
																$items = Yii::$app->request->post()['Product'];
																
																foreach ($items as $item)
																{
																				if ($item['name'] && $item['url'] && $item['priceElement'])
																				{
																								if (Product::create($item)) { $good++; }
																								$total++;
																				}
																}
																
																if ($good == $total && $total > 0) { Yii::$app->session->setFlash('success', "$good of $total products were added to the database."); }
																if ($good != $total && $good > 0 && $total > 0) { Yii::$app->session->setFlash('warning', "$good of $total products were added to the database."); }
																if ($good == 0 && $total > 0) { Yii::$app->session->setFlash('danger', "$good of $total products were added to the database."); }
																if ($total == 0) { Yii::$app->session->setFlash('warning', "You didn't input any data!"); }
																
												}
												
												$categories = Category::find()->select('name')->all();
												$companies = Company::find()->orderBy('status DESC, name ASC')->all();
												$categoriesArr = [];
												$companiesArr = [];
												
												foreach ($categories as $category)
												{
																$categoriesArr[] = $category->name;
												}
												foreach ($companies as $company)
												{
																$companiesArr[] = $company->status == Company::STATUS_NEW ? $company->name.' (!)' : $company->name;
												}
								
												$categoriesJSON = json_encode($categoriesArr);
												$companiesJSON = json_encode($companiesArr);
												
												return $this->render('create', [
																'model' => $form,
																'categories' => $categoriesJSON,
																'companies' => $companiesJSON,
												]);
								}
								else
								{
												return $this->redirect(Url::to(['site/login']));
								}
    }
				
				public function actionApprove($id)
				{
								if (!Yii::$app->user->isGuest && Yii::$app->user->identity->role == User::ROLE_ADMIN)
								{												
												$product = (new Product)->getById($id);
												if ($product !== null)
												{
																$product->status = Product::STATUS_APPROVED;
																$product->save();
												}
												
												return $this->goBack();
								}
								else
								{
												return $this->redirect(Url::to(['site/login']));
								}
				}
    
    public function actionDelete($id)
    {
        if (!Yii::$app->user->isGuest && Yii::$app->user->identity->role == User::ROLE_ADMIN)
								{												
												$product = (new Product)->getById($id);
												if ($product !== null) 
												{ 
																Subscription::deleteAll(['productId' => $id]);
																$product->delete(); 
												}
												
												return $this->goBack();
								}
								else
								{
												return $this->redirect(Url::to(['site/login']));
								}
    }
				
				public function actionHelp()
				{
								return $this->render('help');
				}
				
				public function actionAjaxConvert($value, $from, $to)
				{
								return Yii::$app->formatter->asCurrency(CurrencyHelper::convert($value, $from, $to), CurrencyHelper::getSymbol($to));
				}
				
				public function actionAjaxPrice($id)
				{
							 $p = Product::findOne(['id' => $id]);
								
								if (is_numeric($p->price) && $p->price != 0)
								{
												return Yii::$app->formatter->asCurrency($p->price, CurrencyHelper::getSymbol($p->priceCurrency));
								}	
								throw new Exception('Price retrieve error');
				}
				
				public function actionAjaxCheckUrl($url)
				{						
								if (filter_var($url, FILTER_VALIDATE_URL))
								{
												stream_context_set_default(['http' => ['method' => 'HEAD']]);
												
												$headers = @get_headers($url);
												
												if($headers)
												{
																return $headers[0];
												}
												return '404';
								}
								
								return 'Not an URL';
				}
}

views/product/create.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\helpers\Url;
use app\helpers\AlertHelper;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */

$this->params['breadcrumbs'][] = $this->title;

$tooltip = "Enter the CSS path of product's price. If you don't know what CSS path is, click the question mark to see how to retrieve it.";
$tooltip2 = "Unapproved companies are marked with (!)";

$maxRows = 15;

?>

<div class="product-create">
				
				<?= AlertHelper::get(); ?>
				
    <p>Enter the product(s) details and press Add.</p>
				
				<div class="info alert-maxReached bg-warning" onclick="dismissAlert()" style="display: none;">
								You can't add more than <?= $maxRows ?> entries at once.
				</div>
				
				<div class="alert alert-info">
								Before you add any product, go to products list and disable "only approved".
								Don't duplicate products that do not display an error instead of price.
				</div>

    <?php $form = ActiveForm::begin([
        'id' => 'create-form',
        'options' => ['class' => 'form-horizontal'],
    ]); ?>

				<div class="product-form row">
								<div class="row header">
												<div class="name">Name</div>
												<div class="url">URL</div>
												<div class="priceElement">CSS Path <span data-toggle="popover" data-placement="top" data-trigger="hover" data-content="<?= $tooltip ?>"><a href="<?= Url::to(['product/help']) ?>"><i class="glyphicon glyphicon-question-sign"></i></a></span></div>
												<div class="company">Producer  <span data-toggle="popover" data-placement="top" data-trigger="hover" data-content="<?= $tooltip2 ?>"><i class="glyphicon glyphicon-question-sign"></i></span></div>
												<div class="category">Category</div>
												<div class="button"><i class="glyphicon glyphicon-plus" onclick="addRow()"></i></div>
							 </div>
				</div>

    <div class="row" style="margin-top: 5px; margin-left: -15px;">
        <div class="col-lg-11">
            <?= Html::submitButton('Add', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
        </div>
    </div>

    <?php ActiveForm::end(); ?>
				
				<div class="subscription-add alert-info alert col-lg-4">
								<div>
												<p>The producer is not on the list? Add it!</p>
								</div>
								<form method="get" action="<?= Url::to(['company/create']) ?>">
								<div class="form">
												<div class="col-lg-10">
																<input type="text" name="name" class="form-control" />
												</div>
												<div class="col-lg-2">
																<input type="submit" value="Add" class="btn btn-danger btn-md" />
												</div>
								</div>
								</form>
				</div>
</div>

<script type="text/javascript">

var i = 0;
var rowCount = 0;

var maxRows = <?= $maxRows ?>;

function generateField(attribute, type)
{
				var id = 'product-' + i + '-' + attribute;
				var name = 'Product[' + i + '][' + attribute + ']';
				
				if (type === 'select')
				{
								var options = "";
								
								var optionsJSON = (attribute === 'company') ? <?= $companies ?> : <?= $categories ?>;
							 
								for (var a = 0; a < optionsJSON.length; a++)
								{
												options += '<option>' + optionsJSON[a] + '</option>';
								}
								
								return '<select id="' + id + '" class="form-control" name="' + name + '">' + options + '</select>';
				}
				else
				{
								return '<input type="' + type + '" id="' + id + '" class="form-control" name="' + name + '" />';
				}
}

function addRow()
{
				if (rowCount + 1 < 20)
				{
								$('.product-form').append(
												'<div class="row" id="row-' + i + '">'
															+'<div class="name">' + generateField('name', 'text') + '</div>'
															+'<div class="url">' + generateField('url', 'text') + '</div>'
															+'<div class="priceElement">' + generateField('priceElement', 'text') + '</div>'
															+'<div class="company">' + generateField('company', 'select') + '</div>'
															+'<div class="category">' + generateField('category', 'select') + '</div>'
															+ ((i !== 0) ? '<div class="button"><i class="glyphicon glyphicon-remove" onclick="removeRow(' + i + ')"></i></div>' : '')
											+'</div>'
								);

								i++;
								rowCount++;
				}
				else
				{
								$('.alert-maxReached').show();
				}
}

function removeRow(row)
{
				$('#row-' + row).remove();
				rowCount--;
}				

function dismissAlert()
{
				$('.alert-maxReached').hide();
}

$(document).ready(addRow());
</script>

views/product/help.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;
/* @var $this yii\web\View */
$this->title = 'Help';
$this->params['breadcrumbs'][] = $this->title;
?>

<script type="text/javascript">

$('#chrome a').click(function (e) {
  e.preventDefault()
  $(this).tab('show')
})

$('#firefox a').click(function (e) {
  e.preventDefault()
  $(this).tab('show')
})

$('#iexplorer a').click(function (e) {
  e.preventDefault()
  $(this).tab('show')
})

$('#opera a').click(function (e) {
  e.preventDefault()
  $(this).tab('show')
})

</script>

<div class="product-help">
				<h1>Help</h1>

    <ul class="nav nav-tabs" role="tablist">
								<li role="presentation" class="active"><a href="#chrome-opera" aria-controls="chrome-opera" role="tab" data-toggle="tab">Chrome / Opera</a></li>
								<li role="presentation"><a href="#firefox" aria-controls="firefox" role="tab" data-toggle="tab">Firefox</a></li>
								<li role="presentation"><a href="#iexplorer" aria-controls="iexplorer" role="tab" data-toggle="tab">Internet Explorer</a></li>
				</ul>

				<div class="tab-content">
								<div role="tabpanel" class="tab-pane active" id="chrome-opera">
												<h3>Step 1: Determining the URL</h3>
												<p>Go to the producer's website and choose the product you want to add. Then, copy the full URL and paste it in the URL field.</p>
												<img style="width: 100%" src="<?= Url::to('@web/img/help/chrome/url.png'); ?>" />
												
												<h3>Step 2: Opening the Inspector</h3>
												<p>Right click the price and choose <b>"Inspect Element"</b>.</p>
												<img style="width: 100%" src="<?= Url::to('@web/img/help/chrome/inspect_element.jpg'); ?>" />
												
												<h3>Step 3: Determining the CSS path</h3>
												<p>Right click the price in the inspector window and choose <b>"Copy CSS Path"</b>. 
																				Make sure there is nothing else but price in the area (check what the inspector is highlighting), or the system might not and most probably 
																				will not be able to retrieve the price. Then paste the path in the CSS Path field.</p>
												<img style="width: 100%" src="<?= Url::to('@web/img/help/chrome/css_path.png'); ?>" />
												<p>
							 </div>
								<div role="tabpanel" class="tab-pane" id="firefox">
												<h3>Step 1: Determining the URL</h3>
												<p>Go to the producer's website and choose the product you want to add. Then, copy the full URL and paste it in the URL field.</p>
												<img style="width: 100%" src="<?= Url::to('@web/img/help/firefox/url.png'); ?>" />
												
												<h3>Step 2: Opening the Inspector</h3>
												<p>Right click the price and choose <b>"Inspect Element"</b>.</p>
												<img style="width: 100%" src="<?= Url::to('@web/img/help/firefox/inspect_element.jpg'); ?>" />
												
												<h3>Step 3: Determining the CSS path</h3>
												<p>Right click the price in the inspector window and choose <b>"Copy Unique Selector"</b>. 
																				Make sure there is nothing else but price in the area (check what the inspector is highlighting), or the system might not and most probably 
																				will not be able to retrieve the price. Then paste the path in the CSS Path field.</p>
												<img style="width: 100%" src="<?= Url::to('@web/img/help/firefox/css_path.png'); ?>" />
												<p>
								</div>
								<div role="tabpanel" class="tab-pane" id="iexplorer">
												<h3>Step 1: Determining the URL</h3>
												<p>Go to the producer's website and choose the product you want to add. Then, copy the full URL and paste it in the URL field.</p>
												<img style="width: 100%" src="<?= Url::to('@web/img/help/iexplorer/url.png'); ?>" />
												
												<h3>Step 2: Opening the Inspector</h3>
												<p>Right click the price and choose something along the lines of <b>"Inspect Element"</b> or <b>"Check Element"</b>. Unfortunately I wasn't able to install English version
												of IE on my computer, so the screenshot is in Polish.</p>
												<img style="width: 100%" src="<?= Url::to('@web/img/help/iexplorer/inspect_element.png'); ?>" />
												
												<h3>Step 3: Determining the CSS path</h3>
												<p>Unfortunately, IE doesn't allow you to copy the path so you have to manually type it in the field. Best practice is to use last two selectors and separate them
																				with space. For this example, the CSS path would be: <code>div.intro-inner p.excerpt</code></p>
												<img style="width: 100%" src="<?= Url::to('@web/img/help/iexplorer/css_path.jpg'); ?>" />
												<p></div>
				</div>
</div>

views/product/list.php
<?php

use yii\grid\GridView;
use yii\helpers\Html;
use app\helpers\StarRatingHelper;
use app\helpers\CurrencyHelper;
use yii\helpers\Url;
use app\helpers\AlertHelper;

echo AlertHelper::get();

?> 
<div class="row">
				<div style="font-size: 20px" class="col-md-6"> 
								<?php
								if ($onlyApproved) {echo Html::a('Only approved <i class="fa fa-toggle-on fa-lg" style="color: #070;"></i>', Url::to(['product/list', 'onlyApproved' => 0]), ['class' => 'toggle-approved']);}
								else	{echo Html::a('Only approved <i class="fa fa-toggle-off fa-lg" style="color: #900;"></i>', Url::to(['product/list', 'onlyApproved' => 1]), ['class' => 'toggle-approved']);}
								?> 
				</div>
				<div class="col-md-6">
								<form name="search" class="form-horizontal" method="get" action="<?= Url::to(['product/list']) ?>">
												<div class="input-group form-group">
																								<input class="form-control" id="search" name="search" type="text" placeholder="Search..." <?= isset($search) && $search !== null ? 'value="'.$search.'"' : '' ?>/>
																								<span class="input-group-addon submit" style="border-radius: 0;" onclick="function(){submit();}"><i class="fa fa-search fa-fw"></i></span>
												</div>
								</form>				
				</div>
</div>
<?php

echo GridView::widget([
	'id' => 'product-list',
	'summary' => '',
    'dataProvider' => $provider,
    'columns' => array_merge([
        'name' => [
			'format' => 'html',
			'value' => function($data){
				return	Html::a($data->name, $data->url);
			},
			'label' => 'Name',
			'attribute' => 'name',
			'contentOptions' => ['class' => 'name'],
		],
		'rating' => [
			'format' => 'raw',
			'value' => function($data){
				return StarRatingHelper::getStars($data->rating, $data->id, !Yii::$app->user->isGuest);
			},
			'label' => 'Rating',
			'contentOptions' => ['class' => 'text-center nowrap'],
			'attribute' => 'rating',
		],
        'company.name:text:Producer',
        'category.name:text:Category',
        'price' => [
			'format' => 'html',
            'value' => function($data){
                return '<span class="price">'.
					(is_numeric($data->price) && $data->price != 0 ? Yii::$app->formatter->asCurrency($data->price, CurrencyHelper::getSymbol($data->priceCurrency))
					: '<span class="label label-danger">Error 404</span>')
					.'</span>';
            },
            'label' => 'Price',
			'contentOptions' => ['class' => 'text-right nowrap'],
        ],
		'unifiedPrice' => [
			'format' => 'raw',
			'value' => function($data){
				$userCurrency = Yii::$app->user->isGuest ? 'USD' : Yii::$app->user->identity->currency;
																
				$dataAttributes = $userCurrency == $data->priceCurrency 
					? 'data-noupdate="true"'
					: 'data-value="'.$data->price.'" data-from="'.$data->priceCurrency.'" data-to="'.$userCurrency.'"';
													   
				$content = $userCurrency == $data->priceCurrency
					?  Yii::$app->formatter->asCurrency($data->price, CurrencyHelper::getSymbol($data->priceCurrency))
					: '<i class="fa fa-gear fa-spin"></i>';
																
				return  '<span class="price-unified" '.$dataAttributes.'>'.$content.'</span>';
			},
			'label' => 'Unified price',
			'attribute' => 'unifiedPrice',
			'sortLinkOptions' => ['class' => 'sort-numerical'],
			'contentOptions' => ['class' => 'text-right nowrap'],
		], 
    ],										
	Yii::$app->user->isGuest ? ([] : [
		'subscription' => [
			'value' => function($data){
				return Yii::$app->user->identity->hasSubscription($data->id)
					? Html::a('', Url::to(['subscription/remove', 'product' => $data->id]))
					: Html::a('', Url::to(['subscription/add', 'product' => $data->id]));
				},
				'format' => 'raw',
				'contentOptions' => function($data){
					return ['class' => Yii::$app->user->identity->hasSubscription($data->id)?'has-subscription':'no-subscription'];
				}
			]
		]),
]);
												

?>

<script type="text/javascript">
$(document).ready(function(){
			 $('#product-list table tbody tr').each(function(){
								if (!$(this).find(".price-unified").data('noupdate'))
								{			
												var value = $(this).find(".price-unified").data('value');
												var to = $(this).find(".price-unified").data('to');
												var from = $(this).find(".price-unified").data('from');
												
												var id = $(this).data('key');
												
												$.ajax({
																url: '<?= Url::to(['product/ajax-convert']) ?>' + '?value='+value+'&from='+from+'&to='+to,
																method: 'get',
												}).done(function(data){
															 update(id, data);
												});
								}
			 });
				
				$('.submit').click(function(){
								document.forms['search'].submit();
				});
});

function update(id, price)
{
				$(document).find('[data-key='+id+'] .price-unified').text(price);
}				
</script>